version: '3'

services:
  database:
    image: scylladb/scylla
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
      - 9180:9180
      - 10000:10000
  api-core:
    build: .
    links:
      - database
    environment:
      - SERVER_NAME=Paperwork
      - SERVER_LOGLEVEL=20
      - SERVER_PORT=3000
      - SERVER_BODYPARSER_FORMLIMIT=56kb
      - SERVER_BODYPARSER_JSONLIMIT=10mb
      - SERVER_BODYPARSER_TEXTLIMIT=10mb
      - SERVER_MODULES=users
      - SERVER_COLLECTIONS=user
      - SERVER_PASSWORDS_SALTROUNDS=10
      - SERVER_JWT_ACCESS_EXPIRY=3000
      - SERVER_JWT_REFRESH_EXPIRY=3600
      - DATABASE_DRIVER=cql
      - "DATABASE_CONNECTION={ \"contactPoints\": [\"database\"], \"keyspace\": \"paperwork\" }"
      - "DATABASE_OPTIONS={}"
      - JWT_SECRET=70B3C7BC1954CE09F4282B963E628FD6B586100CF8C21678FF4CAA1D04128FD5
    ports:
      - 3000:3000
