version: '3'
networks:
  papernet:
    driver: overlay
    driver_opts:
      encrypted: "true"
  xnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.10.0/24

services:
  service-discovery:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    networks:
      - papernet
    ports:
      - "8500:8500"
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1

  service-lbx:
    build: service-lbx/
    depends_on:
      - service-discovery
    networks:
      - papernet
      - xnet
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    expose:
      - 8000
      - 8443
      - 8001
      - 8444
    links:
      - service-discovery

  database-kong:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - papernet

  service-kong:
    build: service-kong/
    depends_on:
      - database-kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=database-kong
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    networks:
      - papernet
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    links:
      - devproxy

  database:
    image: scylladb/scylla:latest
    networks:
      - papernet
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
      - 9180:9180
      - 10000:10000

  devproxy:
    build: devproxy/
    networks:
      - papernet
      - xnet
    ports:
      - "2222:22"
    expose:
      - 3000
